// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtBsUt65iKcXeXvfMjNwHB1VWcYgZ-ls',
    appId: '1:410369849677:web:f3f967bd3414d9d310df04',
    messagingSenderId: '410369849677',
    projectId: 'prompt-adda',
    authDomain: 'prompt-adda.firebaseapp.com',
    storageBucket: 'prompt-adda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrJVCQP2f1ODDqpbc5ki3GqyxahMC6Yc',
    appId: '1:410369849677:android:4e794e1214051ec010df04',
    messagingSenderId: '410369849677',
    projectId: 'prompt-adda',
    storageBucket: 'prompt-adda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPyuODIq3lbaYhEgaycToXq5D62s36-h4',
    appId: '1:410369849677:ios:2083aa0276929b5e10df04',
    messagingSenderId: '410369849677',
    projectId: 'prompt-adda',
    storageBucket: 'prompt-adda.firebasestorage.app',
    iosBundleId: 'com.example.promptAdda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPyuODIq3lbaYhEgaycToXq5D62s36-h4',
    appId: '1:410369849677:ios:2083aa0276929b5e10df04',
    messagingSenderId: '410369849677',
    projectId: 'prompt-adda',
    storageBucket: 'prompt-adda.firebasestorage.app',
    iosBundleId: 'com.example.promptAdda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvtBsUt65iKcXeXvfMjNwHB1VWcYgZ-ls',
    appId: '1:410369849677:web:5abdfa8d1a09d95f10df04',
    messagingSenderId: '410369849677',
    projectId: 'prompt-adda',
    authDomain: 'prompt-adda.firebaseapp.com',
    storageBucket: 'prompt-adda.firebasestorage.app',
  );
}
